# Generated by Django 5.1.2 on 2024-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
