# Generated by Django 5.1.2 on 2024-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0003_productmodel_itempicturelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='itemPictureLocation',
            field=models.CharField(max_length=50),
        ),
    ]
