# Generated by Django 5.1.2 on 2024-11-21 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApi', '0004_alter_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Category',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
